/* Definition for the BI_ACCOUNT_ID trigger :  */

CREATE TRIGGER BI_ACCOUNT_ID FOR ACCOUNT
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
      NEW.ID = GEN_ID(ACCOUNT_ID_GEN, 1);
END