/* Definition for the BI_MESSAGE_FILE_ID trigger :  */

CREATE TRIGGER BI_MESSAGE_FILE_ID FOR MESSAGE_FILE
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
      NEW.ID = GEN_ID(MESSAGE_FILE_ID_GEN, 1);
END