/* Definition for the BI_PEER_ADDRESS_ID trigger :  */

CREATE TRIGGER BI_PEER_ADDRESS_ID FOR PEER_ADDRESS
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
      NEW.ID = GEN_ID(PEER_ADDRESS_ID_GEN, 1);
END