/* Definition for the BI_APPCONFIG_ID trigger :  */

CREATE TRIGGER BI_APPCONFIG_ID FOR APPCONFIG
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
      NEW.ID = GEN_ID(APPCONFIG_ID_GEN, 1);
END