/* Definition for the GET_MESSAGE_DETAIL procedure :  */

------------------------------------------------------------------------------
-- Create date: 2020-02-15
-- Autor: Luis Lema
--
-- Description: 
-- Get the details of a message.
--
-- Parameters:
-- ID_MESSAGE - The id of message
--
-- Returns:
-- Metadata of message.
------------------------------------------------------------------------------

CREATE OR ALTER PROCEDURE GET_MESSAGE_DETAIL
(
  ID_MESSAGE TYPE OF COLUMN MESSAGE.ID
)
RETURNS
(
  SENDER_TOKEN TYPE OF COLUMN PEER.TOKEN,
  RECEIVER_TOKEN TYPE OF COLUMN PEER.TOKEN,
  CONTENT TYPE OF COLUMN MESSAGE_TEXT.CONTENT,
  CONTENT_TYPE TYPE OF COLUMN MESSAGE.CONTENT_TYPE,
  UID TYPE OF COLUMN MESSAGE.UID,
  TIMEID BIGINT,
  ARRIVE_DATE TIMESTAMP,
  ID_REPLY TYPE OF COLUMN MESSAGE.ID_REPLY,
  STATE INTEGER
)
AS
DECLARE VARIABLE ACCOUNT_TOKEN TYPE OF COLUMN ACCOUNT.TOKEN;
BEGIN

   ACCOUNT_TOKEN=(SELECT TOKEN FROM ACCOUNT);
   
   FOR 
   SELECT
   CASE A.ID_SENDER
        WHEN 0 THEN :ACCOUNT_TOKEN
        ELSE B.TOKEN
   END,
   CASE A.ID_RECEIVER
        WHEN 0 THEN :ACCOUNT_TOKEN
        ELSE C.TOKEN
   END,
   T.CONTENT,
   A.CONTENT_TYPE, 
   A.UID,
   A.TIMEID,
   A.REG_DATE,
   A.ID_REPLY,
   A.STATE
   FROM MESSAGE A JOIN MESSAGE_TEXT T
   ON A.ID=T.ID_MESSAGE
   LEFT JOIN PEER B
   ON A.ID_SENDER=B.ID
   LEFT JOIN PEER C
   ON A.ID_RECEIVER=C.ID
   WHERE
   A.ID=:ID_MESSAGE
   INTO :SENDER_TOKEN,:RECEIVER_TOKEN,:CONTENT,:CONTENT_TYPE,:UID,:TIMEID,:ARRIVE_DATE,:ID_REPLY,:STATE
   DO
   SUSPEND;
END