/* Structure for the ANIMATION table :  */

CREATE TABLE ANIMATION 
(
  ID INTEGER NOT NULL,
  ID_FILE VARCHAR(256),
  ID_MESSAGE INTEGER,
  WIDTH INTEGER,
  HEIGHT INTEGER,
  CONTENT BLOB
);

ALTER TABLE ANIMATION ADD PRIMARY KEY (ID);