/* Structure for the PEER table :  */

CREATE TABLE PEER 
(
  ID INTEGER NOT NULL,
  TOKEN VARCHAR(64) NOT NULL,
  STATE SMALLINT,
  USER_NAME VARCHAR(64),
  SLOGAN VARCHAR(256),
  AVATAR BLOB,
  GROUP_NAME VARCHAR(64),
  REG_DATE TIMESTAMP NOT NULL,
  CERT BLOB NOT NULL,
  FULL_NAME BLOB,
  DISPLAY_NAME BLOB,
  HEX_COLOR VARCHAR(32),
  INITIALS VARCHAR(32)
);

ALTER TABLE PEER ADD CONSTRAINT PK_PEER PRIMARY KEY (ID);


CREATE INDEX IDX_PEER_01 ON PEER(TOKEN);