SET TERM ^ ;
/* Definition for the SAVE_TEXT_MESSAGE procedure :  */

------------------------------------------------------------------------------
-- Create date: 2020-02-15
-- Autor: Luis Lema
--
-- Description: 
-- Save a text message which is a header of any type of message.
--
-- Parameters:
-- SENDER_TOKEN - The sender of the message.
-- RECEIVER_TOKEN - The receiver of the message.
-- REG_DATE - The date that the message was created.
-- CONTENT - The detail of message.
-- CONTENT_TYPE - The type of message.
-- UID - The UID (Universal ID) of message.
-- TIMEID - The number of ticks (100 nanoseconds) from UTC standard.
-- ID_REPLY - The id of message being replied (It may not be set).
-- THUMBNAIL - The thumbnail of message if there is any.
-- FILE_PATH - The path of cache file (form file messages only)
--
-- Returns:
-- The internal id (number) of message.
------------------------------------------------------------------------------

CREATE OR ALTER PROCEDURE SAVE_TEXT_MESSAGE
(
  SENDER_TOKEN TYPE OF COLUMN PEER.TOKEN,
  RECEIVER_TOKEN TYPE OF COLUMN PEER.TOKEN,
  REG_DATE TYPE OF COLUMN MESSAGE.REG_DATE,
  CONTENT TYPE OF COLUMN MESSAGE_TEXT.CONTENT,
  CONTENT_TYPE TYPE OF COLUMN MESSAGE.CONTENT_TYPE,
  UID TYPE OF COLUMN MESSAGE.UID,
  TIMEID BIGINT,
  ID_REPLY TYPE OF COLUMN MESSAGE.ID_REPLY DEFAULT NULL,
  THUMBNAIL BLOB DEFAULT NULL,
  FILE_PATH BLOB DEFAULT NULL
)
RETURNS
(
  ID_MSG TYPE OF COLUMN MESSAGE.ID
)
AS

DECLARE VARIABLE TODAY TIMESTAMP;
DECLARE VARIABLE ID_SENDER_TOKEN INTEGER;
DECLARE VARIABLE ID_RECEIVER_TOKEN INTEGER;
DECLARE VARIABLE SELF_TOKEN TYPE OF COLUMN ACCOUNT.TOKEN;
DECLARE VARIABLE ID_MESSAGE INTEGER;
DECLARE VARIABLE IS_READ BOOLEAN;
DECLARE VARIABLE ISFILE BOOLEAN;
BEGIN
    SELF_TOKEN=(SELECT TOKEN FROM ACCOUNT);
    
    IF(:SELF_TOKEN=:SENDER_TOKEN)THEN
    BEGIN
       ID_SENDER_TOKEN=0;
    END
    ELSE
    BEGIN
       ID_SENDER_TOKEN=(SELECT ID FROM PEER WHERE TOKEN=:SENDER_TOKEN);  
    END
    
    IF(:SELF_TOKEN=:RECEIVER_TOKEN)THEN
    BEGIN
       ID_RECEIVER_TOKEN=0;
    END
    ELSE
    BEGIN
       ID_RECEIVER_TOKEN=(SELECT ID FROM PEER WHERE TOKEN=:RECEIVER_TOKEN);  
    END
    
    TODAY=(SELECT CURRENT_TIMESTAMP FROM RDB$DATABASE);
    
    --Message is being sent by current user
    IF(ID_SENDER_TOKEN=0) THEN
       IS_READ='TRUE';
    ELSE
       IS_READ='FALSE';
       
    ISFILE=IIF(:CONTENT_TYPE IN(6,7,8,9),'FALSE','TRUE');
       
    --Save message header for text messages
    IF(:ISFILE='FALSE')THEN
    BEGIN
    INSERT INTO MESSAGE(ID_SENDER,ID_RECEIVER,REG_DATE,READ_STATE,CONTENT_TYPE,UID,ID_REPLY,TIMEID)
    VALUES(:ID_SENDER_TOKEN,:ID_RECEIVER_TOKEN,:REG_DATE,:IS_READ,:CONTENT_TYPE,:UID,:ID_REPLY,:TIMEID)
    RETURNING ID
    INTO :ID_MESSAGE;
    END
    ELSE 
    BEGIN --Save message header for file messages
      --STATE -1=INCOMPLETE MESSAGE BECAUSE ACTUAL FILE IS PENDING TO BE SAVED
      INSERT INTO MESSAGE(ID_SENDER,ID_RECEIVER,REG_DATE,READ_STATE,CONTENT_TYPE,UID,ID_REPLY,STATE,TIMEID)
	  VALUES(:ID_SENDER_TOKEN,:ID_RECEIVER_TOKEN,:REG_DATE,:IS_READ,:CONTENT_TYPE,:UID,:ID_REPLY,-1,:TIMEID)
      RETURNING ID
	  INTO :ID_MESSAGE;
    END
    
    --Get generated id message
    ID_MSG=:ID_MESSAGE;
    
    --Save message content
    INSERT INTO MESSAGE_TEXT(ID_MESSAGE,CONTENT)
    VALUES(:ID_MSG,:CONTENT);
    
    --Check if message is a file
    IF(:ISFILE='TRUE') THEN
    BEGIN
       INSERT INTO MESSAGE_FILE(ID_MESSAGE,THUMBN,FPATH)
       VALUES(:ID_MESSAGE,:THUMBNAIL,:FILE_PATH);
    END
    
    IF(:SELF_TOKEN<>:SENDER_TOKEN) THEN
    BEGIN
        INSERT INTO MESSAGE_NOTIFICATION(ID_SENDER,ID_MESSAGE,CONTENT_TYPE)
        VALUES(:ID_SENDER_TOKEN,:ID_MESSAGE,:CONTENT_TYPE);
    END
END^