/* Definition for the BI_MESSAGE_TEXT_ID trigger :  */

CREATE TRIGGER BI_MESSAGE_TEXT_ID FOR MESSAGE_TEXT
ACTIVE BEFORE 
  INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
      NEW.ID = GEN_ID(MESSAGE_TEXT_ID_GEN, 1);
END