/* Structure for the CONNSTR table :  */

CREATE TABLE CONNSTR (
  ID INTEGER NOT NULL,
  IDKEY VARCHAR(190) NOT NULL,
  STR BLOB);

  ALTER TABLE CONNSTR ADD CONSTRAINT PK_CONNSTR PRIMARY KEY (ID,IDKEY);