/* Structure for the CREDENTIAL table :  */

CREATE TABLE CREDENTIAL 
(
  ID_ACCOUNT INTEGER NOT NULL,
  CERT BLOB NOT NULL
);


ALTER TABLE CREDENTIAL ADD CONSTRAINT PK_CREDENTIAL PRIMARY KEY (ID_ACCOUNT);