/* Structure for the MESSAGE_TEXT table :  */

CREATE TABLE MESSAGE_TEXT 
(
  ID BIGINT,
  ID_MESSAGE BIGINT,
  CONTENT BLOB
);

ALTER TABLE MESSAGE_TEXT ADD CONSTRAINT FK_MESSAGE_TEXT_MESSAGE FOREIGN KEY (ID_MESSAGE) REFERENCES MESSAGE(ID);

CREATE INDEX IDX_MESSAGE_TEXT_01 ON MESSAGE_TEXT(ID_MESSAGE);