/* Structure for the MESSAGE table :  */

CREATE TABLE MESSAGE 
(
  ID BIGINT NOT NULL,
  ID_SENDER INTEGER NOT NULL,
  ID_RECEIPT INTEGER NOT NULL,
  REG_DATE TIMESTAMP NOT NULL,
  UID VARCHAR(10000),
  READ_STATE BOOLEAN NOT NULL,
  CONTENT_TYPE INTEGER,
  ID_REPLY INTEGER,
  PROCESSED BOOLEAN DEFAULT 'FALSE',
  STATE INTEGER default 0,
  TIMEID BIGINT
);


ALTER TABLE MESSAGE ADD CONSTRAINT PK_MESSAGE PRIMARY KEY (ID);


CREATE INDEX IDX_MESSAGE_01 ON MESSAGE(REG_DATE);