/* Structure for the NOTIFICATION table :  */

CREATE TABLE NOTIFICATION 
(
  ID_TOKEN INTEGER NOT NULL,
  REG_DATE TIMESTAMP NOT NULL,
  TYPE_NOT SMALLINT NOT NULL,
  CONTENT VARCHAR(1024),
  PROCESSED BOOLEAN
);