/* Structure for the NOTIFICATION table :  */

CREATE TABLE NOTIFICATION 
(
  ID VARCHAR(128) CHARACTER SET NONE NOT NULL,
  REG_DATE TIMESTAMP NOT NULL,
  TYPE_NOTF SMALLINT NOT NULL,
  CONTENT BLOB
);