/* Structure for the PARTIAL_MESSAGE table :  */

CREATE TABLE PARTIAL_MESSAGE 
(
  ID VARCHAR(256) NOT NULL,
  SEQ INTEGER NOT NULL,
  CONTENT BLOB
);

ALTER TABLE PARTIAL_MESSAGE ADD CONSTRAINT PK_PARTIAL_MESSAGE PRIMARY KEY (ID,SEQ);