/* Structure for the PEER_ADDRESS table :  */

CREATE TABLE PEER_ADDRESS 
(
  ID INTEGER NOT NULL,
  ID_TOKEN INTEGER NOT NULL,
  ADDRESS VARCHAR(128) NOT NULL,
  REG_DATE TIMESTAMP NOT NULL,
  ENABLED BOOLEAN,
  SERV_TYPE VARCHAR(32)
);


ALTER TABLE PEER_ADDRESS ADD CONSTRAINT PK_PEER_ADDRESS PRIMARY KEY (ID);

ALTER TABLE PEER_ADDRESS ADD CONSTRAINT FK_PEER_ADDRESS FOREIGN KEY (ID_TOKEN) REFERENCES PEER(ID);