/* Structure for the APPCONFIG table :  */

CREATE TABLE APPCONFIG (
  ID INTEGER NOT NULL,
  IDKEY VARCHAR(190) NOT NULL,
  VAL BLOB);


ALTER TABLE APPCONFIG ADD CONSTRAINT PK_APPCONFIG PRIMARY KEY (ID,IDKEY);